### ISSUE TITLE
Fix Example in getting-started.md

### ISSUE THREAD

**Issue by brishtibheja** [shigeyukey/anki-manual-jp#1]
I think the example cards are wrong [in this section](<https://shigeyukey.github.io/anki-manual-jp/getting-started.html#%E3%83%8E%E3%83%BC%E3%83%88%E3%81%A8%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89>).

In the Japanese context the cards will be bonjour —> こんにちは (and not hello).

It also might be worth considering changing the examples to languages people in Japan are more aware of. How about a "hello —> こんにちは" card. Less cognitive load is better.

(In parts of the document we also mention 「大きい」 for an English audience so something to keep in mind about examples.)

**Comment by shigeyukey** [comment]
Thank you, I fixed it.

**Comment by brishtibheja** [comment]
@shigeyukey Now the field names are incorrect. In the first example, it's "French", "English" and after that it's corrected to 「フランス語」 and 「日本語」。

I can fix it but you've forked Anki's manual (which I've a fork of) so I'll probably mess up trying to do it from a branch.

**Comment by shigeyukey** [comment]
This part? I think the “English” field means the user's native language, I changed it to “こんにちは”, so maybe “日本語” is the proper field name.


```
    Q: Bonjour
    A: Hello
       Page #12

    Q: {{French}}
    A: {{English}}<br>
       Page #{{Page}}

    Q: {{English}}
    A: {{French}}<br>
       Page #{{Page}}
```

```
    Q: Bonjour
    A: こんにちは
       ページ #12

    Q: {{フランス語}}
    A: {{日本語}}<br>
       ページ #{{ページ}}

    Q: {{日本語}}
    A: {{フランス語}}<br>
       ページ #{{ページ}}
```

**Comment by brishtibheja** [comment]
This part, just before notes/fields are defined:

この例では、3つの関連する情報があります：フランス語の単語、英語の意味、ページ番号です。これらをまとめると、次のようになります：

```
French: Bonjour
English: こんにちは
ページ: 12
```

edit: just noticed the text says 英語の意味

**Comment by shigeyukey** [comment]
Thanks I found it and fixed it.

**Comment by brishtibheja** [comment]
Do you plan to create a seperate repo that is not a fork, otherwise it's a bit hard to contribute.

**Comment by shigeyukey** [comment]
I recreated this repository.
old : anki-manual-jp -> anki-manual-jp_00
new : https://github.com/shigeyukey/anki-manual-jp
